### ISSUE TITLE
Feature request  / docs addition - Replace localhost with web address

### ISSUE THREAD

**Issue by jondo89** [lgraubner/sitemap-generator#75] opened 2020-04-30 12:50 UTC
Hi , Please could you add a feature/explain how to replace the localhost site generator with the final hosting address on the generated maps.

i.e

  <url>
    <loc>http://localhost:5000/</loc>
  </url>

replace with

  <url>
    <loc>http://finaldestination.etc/</loc>
  </url>

**Comment by lgraubner** [comment] 2020-05-04 06:58
That sounds useful. Anyone willing to submit a PR for this?

**Comment by lgraubner** [comment] 2020-05-04 07:00
Duplicate of #65 closing this here.

**Closed by lgraubner** 2020-05-04 07:00 UTC
Labels: enhancement, help wanted
